server:
  port: 2010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1020/eureka?characterEncoding=UTF8&autoReconnect=true&useSSL=false
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: system-server:2010  #指定客户端实例的ID
spring:
  datasource:
    username: root
    password: TaylorSwift
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm_system
  application:
    name: system-server
mybatis-plus:
  type-aliases-package: com.lee.hrm.domain,com.lee.hrm.query