server:
  port: 2012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1020/eureka
  instance:
    prefer-ip-address: true  #使用ip注册到Eureka
    instance-id: course-server:2012  #指定客户端实例的ID
spring:
  datasource:
    username: root
    password: TaylorSwift
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm_course
  application:
    name: course-server
mybatis-plus:
  type-aliases-package: cn.lee.hrm.domain,cn.lee.hrm.query