server:
  port: 2010
spring:
  application:
    name: zuul-server999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka,http://localhost:1020/eureka,http://localhost:1030/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: zuul:2010
zuul:
  routes:
    provider.serviceId: user-provider
    provider.path: "/myProvider/**"  # 把provider起头的所有都分配给user-provider
    consumer.serviceId: user-consumer
    consumer.path: "/myConsumer/**" # 把myConsumer起头的所有部分配个user-consumer
  ignored-services: "*" #所有请求都不可以用服务名来访问
  prefix: "/lee" # 前缀
